// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  coming_soon: dynamic(() => import("./ComingSoon")),
  hero: dynamic(() => import("./Hero")),
  text: dynamic(() => import("./Text")),
};
